// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package pbmsg;

import pbmsg.Msg.CMsg;
import pbmsg.Msg.CMsgHead;
import pbmsg.Msg.CMsgReg;

public final class Msg {
	private Msg() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface CMsgOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required string msghead = 1;
		/**
		 * <code>required string msghead = 1;</code>
		 */
		boolean hasMsghead();

		/**
		 * <code>required string msghead = 1;</code>
		 */
		java.lang.String getMsghead();

		/**
		 * <code>required string msghead = 1;</code>
		 */
		com.google.protobuf.ByteString getMsgheadBytes();

		// required string msgbody = 2;
		/**
		 * <code>required string msgbody = 2;</code>
		 */
		boolean hasMsgbody();

		/**
		 * <code>required string msgbody = 2;</code>
		 */
		java.lang.String getMsgbody();

		/**
		 * <code>required string msgbody = 2;</code>
		 */
		com.google.protobuf.ByteString getMsgbodyBytes();
	}

	/**
	 * Protobuf type {@code pbmsg.CMsg}
	 */
	public static final class CMsg extends com.google.protobuf.GeneratedMessage
			implements CMsgOrBuilder {
		// Use CMsg.newBuilder() to construct.
		private CMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CMsg(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final CMsg defaultInstance;

		public static CMsg getDefaultInstance() {
			return defaultInstance;
		}

		public CMsg getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CMsg(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						msghead_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						msgbody_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return pbmsg.Msg.internal_static_pbmsg_CMsg_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return pbmsg.Msg.internal_static_pbmsg_CMsg_fieldAccessorTable
					.ensureFieldAccessorsInitialized(pbmsg.Msg.CMsg.class,
							pbmsg.Msg.CMsg.Builder.class);
		}

		public static com.google.protobuf.Parser<CMsg> PARSER = new com.google.protobuf.AbstractParser<CMsg>() {
			public CMsg parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CMsg(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CMsg> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required string msghead = 1;
		public static final int MSGHEAD_FIELD_NUMBER = 1;
		private java.lang.Object msghead_;

		/**
		 * <code>required string msghead = 1;</code>
		 */
		public boolean hasMsghead() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required string msghead = 1;</code>
		 */
		public java.lang.String getMsghead() {
			java.lang.Object ref = msghead_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					msghead_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string msghead = 1;</code>
		 */
		public com.google.protobuf.ByteString getMsgheadBytes() {
			java.lang.Object ref = msghead_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				msghead_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string msgbody = 2;
		public static final int MSGBODY_FIELD_NUMBER = 2;
		private java.lang.Object msgbody_;

		/**
		 * <code>required string msgbody = 2;</code>
		 */
		public boolean hasMsgbody() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required string msgbody = 2;</code>
		 */
		public java.lang.String getMsgbody() {
			java.lang.Object ref = msgbody_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					msgbody_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string msgbody = 2;</code>
		 */
		public com.google.protobuf.ByteString getMsgbodyBytes() {
			java.lang.Object ref = msgbody_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				msgbody_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			msghead_ = "";
			msgbody_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasMsghead()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMsgbody()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getMsgheadBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getMsgbodyBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getMsgheadBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getMsgbodyBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static pbmsg.Msg.CMsg parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static pbmsg.Msg.CMsg parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static pbmsg.Msg.CMsg parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static pbmsg.Msg.CMsg parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static pbmsg.Msg.CMsg parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static pbmsg.Msg.CMsg parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static pbmsg.Msg.CMsg parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static pbmsg.Msg.CMsg parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static pbmsg.Msg.CMsg parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static pbmsg.Msg.CMsg parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(pbmsg.Msg.CMsg prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code pbmsg.CMsg}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				pbmsg.Msg.CMsgOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return pbmsg.Msg.internal_static_pbmsg_CMsg_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return pbmsg.Msg.internal_static_pbmsg_CMsg_fieldAccessorTable
						.ensureFieldAccessorsInitialized(pbmsg.Msg.CMsg.class,
								pbmsg.Msg.CMsg.Builder.class);
			}

			// Construct using pbmsg.Msg.CMsg.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				msghead_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				msgbody_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return pbmsg.Msg.internal_static_pbmsg_CMsg_descriptor;
			}

			public pbmsg.Msg.CMsg getDefaultInstanceForType() {
				return pbmsg.Msg.CMsg.getDefaultInstance();
			}

			public pbmsg.Msg.CMsg build() {
				pbmsg.Msg.CMsg result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public pbmsg.Msg.CMsg buildPartial() {
				pbmsg.Msg.CMsg result = new pbmsg.Msg.CMsg(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.msghead_ = msghead_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.msgbody_ = msgbody_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof pbmsg.Msg.CMsg) {
					return mergeFrom((pbmsg.Msg.CMsg) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(pbmsg.Msg.CMsg other) {
				if (other == pbmsg.Msg.CMsg.getDefaultInstance())
					return this;
				if (other.hasMsghead()) {
					bitField0_ |= 0x00000001;
					msghead_ = other.msghead_;
					onChanged();
				}
				if (other.hasMsgbody()) {
					bitField0_ |= 0x00000002;
					msgbody_ = other.msgbody_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasMsghead()) {

					return false;
				}
				if (!hasMsgbody()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				pbmsg.Msg.CMsg parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (pbmsg.Msg.CMsg) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required string msghead = 1;
			private java.lang.Object msghead_ = "";

			/**
			 * <code>required string msghead = 1;</code>
			 */
			public boolean hasMsghead() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string msghead = 1;</code>
			 */
			public java.lang.String getMsghead() {
				java.lang.Object ref = msghead_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					msghead_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string msghead = 1;</code>
			 */
			public com.google.protobuf.ByteString getMsgheadBytes() {
				java.lang.Object ref = msghead_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					msghead_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string msghead = 1;</code>
			 */
			public Builder setMsghead(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				msghead_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string msghead = 1;</code>
			 */
			public Builder clearMsghead() {
				bitField0_ = (bitField0_ & ~0x00000001);
				msghead_ = getDefaultInstance().getMsghead();
				onChanged();
				return this;
			}

			/**
			 * <code>required string msghead = 1;</code>
			 */
			public Builder setMsgheadBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				msghead_ = value;
				onChanged();
				return this;
			}

			// required string msgbody = 2;
			private java.lang.Object msgbody_ = "";

			/**
			 * <code>required string msgbody = 2;</code>
			 */
			public boolean hasMsgbody() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string msgbody = 2;</code>
			 */
			public java.lang.String getMsgbody() {
				java.lang.Object ref = msgbody_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					msgbody_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string msgbody = 2;</code>
			 */
			public com.google.protobuf.ByteString getMsgbodyBytes() {
				java.lang.Object ref = msgbody_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					msgbody_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string msgbody = 2;</code>
			 */
			public Builder setMsgbody(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				msgbody_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string msgbody = 2;</code>
			 */
			public Builder clearMsgbody() {
				bitField0_ = (bitField0_ & ~0x00000002);
				msgbody_ = getDefaultInstance().getMsgbody();
				onChanged();
				return this;
			}

			/**
			 * <code>required string msgbody = 2;</code>
			 */
			public Builder setMsgbodyBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				msgbody_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:pbmsg.CMsg)
		}

		static {
			defaultInstance = new CMsg(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:pbmsg.CMsg)
	}

	public interface CMsgHeadOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// optional int32 msglen = 1;
		/**
		 * <code>optional int32 msglen = 1;</code>
		 */
		boolean hasMsglen();

		/**
		 * <code>optional int32 msglen = 1;</code>
		 */
		int getMsglen();

		// optional int32 msgtype = 2;
		/**
		 * <code>optional int32 msgtype = 2;</code>
		 */
		boolean hasMsgtype();

		/**
		 * <code>optional int32 msgtype = 2;</code>
		 */
		int getMsgtype();

		// optional int32 msgseq = 3;
		/**
		 * <code>optional int32 msgseq = 3;</code>
		 */
		boolean hasMsgseq();

		/**
		 * <code>optional int32 msgseq = 3;</code>
		 */
		int getMsgseq();

		// optional int32 termversion = 4;
		/**
		 * <code>optional int32 termversion = 4;</code>
		 */
		boolean hasTermversion();

		/**
		 * <code>optional int32 termversion = 4;</code>
		 */
		int getTermversion();

		// optional int32 msgres = 5;
		/**
		 * <code>optional int32 msgres = 5;</code>
		 */
		boolean hasMsgres();

		/**
		 * <code>optional int32 msgres = 5;</code>
		 */
		int getMsgres();

		// optional string termid = 6;
		/**
		 * <code>optional string termid = 6;</code>
		 */
		boolean hasTermid();

		/**
		 * <code>optional string termid = 6;</code>
		 */
		java.lang.String getTermid();

		/**
		 * <code>optional string termid = 6;</code>
		 */
		com.google.protobuf.ByteString getTermidBytes();
	}

	/**
	 * Protobuf type {@code pbmsg.CMsgHead}
	 */
	public static final class CMsgHead extends
			com.google.protobuf.GeneratedMessage implements CMsgHeadOrBuilder {
		// Use CMsgHead.newBuilder() to construct.
		private CMsgHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CMsgHead(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final CMsgHead defaultInstance;

		public static CMsgHead getDefaultInstance() {
			return defaultInstance;
		}

		public CMsgHead getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CMsgHead(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						msglen_ = input.readInt32();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						msgtype_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						msgseq_ = input.readInt32();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						termversion_ = input.readInt32();
						break;
					}
					case 40: {
						bitField0_ |= 0x00000010;
						msgres_ = input.readInt32();
						break;
					}
					case 50: {
						bitField0_ |= 0x00000020;
						termid_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return pbmsg.Msg.internal_static_pbmsg_CMsgHead_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return pbmsg.Msg.internal_static_pbmsg_CMsgHead_fieldAccessorTable
					.ensureFieldAccessorsInitialized(pbmsg.Msg.CMsgHead.class,
							pbmsg.Msg.CMsgHead.Builder.class);
		}

		public static com.google.protobuf.Parser<CMsgHead> PARSER = new com.google.protobuf.AbstractParser<CMsgHead>() {
			public CMsgHead parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CMsgHead(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CMsgHead> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// optional int32 msglen = 1;
		public static final int MSGLEN_FIELD_NUMBER = 1;
		private int msglen_;

		/**
		 * <code>optional int32 msglen = 1;</code>
		 */
		public boolean hasMsglen() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>optional int32 msglen = 1;</code>
		 */
		public int getMsglen() {
			return msglen_;
		}

		// optional int32 msgtype = 2;
		public static final int MSGTYPE_FIELD_NUMBER = 2;
		private int msgtype_;

		/**
		 * <code>optional int32 msgtype = 2;</code>
		 */
		public boolean hasMsgtype() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional int32 msgtype = 2;</code>
		 */
		public int getMsgtype() {
			return msgtype_;
		}

		// optional int32 msgseq = 3;
		public static final int MSGSEQ_FIELD_NUMBER = 3;
		private int msgseq_;

		/**
		 * <code>optional int32 msgseq = 3;</code>
		 */
		public boolean hasMsgseq() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional int32 msgseq = 3;</code>
		 */
		public int getMsgseq() {
			return msgseq_;
		}

		// optional int32 termversion = 4;
		public static final int TERMVERSION_FIELD_NUMBER = 4;
		private int termversion_;

		/**
		 * <code>optional int32 termversion = 4;</code>
		 */
		public boolean hasTermversion() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional int32 termversion = 4;</code>
		 */
		public int getTermversion() {
			return termversion_;
		}

		// optional int32 msgres = 5;
		public static final int MSGRES_FIELD_NUMBER = 5;
		private int msgres_;

		/**
		 * <code>optional int32 msgres = 5;</code>
		 */
		public boolean hasMsgres() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		/**
		 * <code>optional int32 msgres = 5;</code>
		 */
		public int getMsgres() {
			return msgres_;
		}

		// optional string termid = 6;
		public static final int TERMID_FIELD_NUMBER = 6;
		private java.lang.Object termid_;

		/**
		 * <code>optional string termid = 6;</code>
		 */
		public boolean hasTermid() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		/**
		 * <code>optional string termid = 6;</code>
		 */
		public java.lang.String getTermid() {
			java.lang.Object ref = termid_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					termid_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string termid = 6;</code>
		 */
		public com.google.protobuf.ByteString getTermidBytes() {
			java.lang.Object ref = termid_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				termid_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			msglen_ = 0;
			msgtype_ = 0;
			msgseq_ = 0;
			termversion_ = 0;
			msgres_ = 0;
			termid_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, msglen_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, msgtype_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, msgseq_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt32(4, termversion_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeInt32(5, msgres_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeBytes(6, getTermidBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, msglen_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, msgtype_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, msgseq_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						4, termversion_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						5, msgres_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						6, getTermidBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static pbmsg.Msg.CMsgHead parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgHead parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static pbmsg.Msg.CMsgHead parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static pbmsg.Msg.CMsgHead parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(pbmsg.Msg.CMsgHead prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code pbmsg.CMsgHead}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				pbmsg.Msg.CMsgHeadOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return pbmsg.Msg.internal_static_pbmsg_CMsgHead_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return pbmsg.Msg.internal_static_pbmsg_CMsgHead_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								pbmsg.Msg.CMsgHead.class,
								pbmsg.Msg.CMsgHead.Builder.class);
			}

			// Construct using pbmsg.Msg.CMsgHead.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				msglen_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				msgtype_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				msgseq_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				termversion_ = 0;
				bitField0_ = (bitField0_ & ~0x00000008);
				msgres_ = 0;
				bitField0_ = (bitField0_ & ~0x00000010);
				termid_ = "";
				bitField0_ = (bitField0_ & ~0x00000020);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return pbmsg.Msg.internal_static_pbmsg_CMsgHead_descriptor;
			}

			public pbmsg.Msg.CMsgHead getDefaultInstanceForType() {
				return pbmsg.Msg.CMsgHead.getDefaultInstance();
			}

			public pbmsg.Msg.CMsgHead build() {
				pbmsg.Msg.CMsgHead result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public pbmsg.Msg.CMsgHead buildPartial() {
				pbmsg.Msg.CMsgHead result = new pbmsg.Msg.CMsgHead(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.msglen_ = msglen_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.msgtype_ = msgtype_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.msgseq_ = msgseq_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.termversion_ = termversion_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.msgres_ = msgres_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.termid_ = termid_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof pbmsg.Msg.CMsgHead) {
					return mergeFrom((pbmsg.Msg.CMsgHead) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(pbmsg.Msg.CMsgHead other) {
				if (other == pbmsg.Msg.CMsgHead.getDefaultInstance())
					return this;
				if (other.hasMsglen()) {
					setMsglen(other.getMsglen());
				}
				if (other.hasMsgtype()) {
					setMsgtype(other.getMsgtype());
				}
				if (other.hasMsgseq()) {
					setMsgseq(other.getMsgseq());
				}
				if (other.hasTermversion()) {
					setTermversion(other.getTermversion());
				}
				if (other.hasMsgres()) {
					setMsgres(other.getMsgres());
				}
				if (other.hasTermid()) {
					bitField0_ |= 0x00000020;
					termid_ = other.termid_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				pbmsg.Msg.CMsgHead parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (pbmsg.Msg.CMsgHead) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// optional int32 msglen = 1;
			private int msglen_;

			/**
			 * <code>optional int32 msglen = 1;</code>
			 */
			public boolean hasMsglen() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>optional int32 msglen = 1;</code>
			 */
			public int getMsglen() {
				return msglen_;
			}

			/**
			 * <code>optional int32 msglen = 1;</code>
			 */
			public Builder setMsglen(int value) {
				bitField0_ |= 0x00000001;
				msglen_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 msglen = 1;</code>
			 */
			public Builder clearMsglen() {
				bitField0_ = (bitField0_ & ~0x00000001);
				msglen_ = 0;
				onChanged();
				return this;
			}

			// optional int32 msgtype = 2;
			private int msgtype_;

			/**
			 * <code>optional int32 msgtype = 2;</code>
			 */
			public boolean hasMsgtype() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional int32 msgtype = 2;</code>
			 */
			public int getMsgtype() {
				return msgtype_;
			}

			/**
			 * <code>optional int32 msgtype = 2;</code>
			 */
			public Builder setMsgtype(int value) {
				bitField0_ |= 0x00000002;
				msgtype_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 msgtype = 2;</code>
			 */
			public Builder clearMsgtype() {
				bitField0_ = (bitField0_ & ~0x00000002);
				msgtype_ = 0;
				onChanged();
				return this;
			}

			// optional int32 msgseq = 3;
			private int msgseq_;

			/**
			 * <code>optional int32 msgseq = 3;</code>
			 */
			public boolean hasMsgseq() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional int32 msgseq = 3;</code>
			 */
			public int getMsgseq() {
				return msgseq_;
			}

			/**
			 * <code>optional int32 msgseq = 3;</code>
			 */
			public Builder setMsgseq(int value) {
				bitField0_ |= 0x00000004;
				msgseq_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 msgseq = 3;</code>
			 */
			public Builder clearMsgseq() {
				bitField0_ = (bitField0_ & ~0x00000004);
				msgseq_ = 0;
				onChanged();
				return this;
			}

			// optional int32 termversion = 4;
			private int termversion_;

			/**
			 * <code>optional int32 termversion = 4;</code>
			 */
			public boolean hasTermversion() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional int32 termversion = 4;</code>
			 */
			public int getTermversion() {
				return termversion_;
			}

			/**
			 * <code>optional int32 termversion = 4;</code>
			 */
			public Builder setTermversion(int value) {
				bitField0_ |= 0x00000008;
				termversion_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 termversion = 4;</code>
			 */
			public Builder clearTermversion() {
				bitField0_ = (bitField0_ & ~0x00000008);
				termversion_ = 0;
				onChanged();
				return this;
			}

			// optional int32 msgres = 5;
			private int msgres_;

			/**
			 * <code>optional int32 msgres = 5;</code>
			 */
			public boolean hasMsgres() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			/**
			 * <code>optional int32 msgres = 5;</code>
			 */
			public int getMsgres() {
				return msgres_;
			}

			/**
			 * <code>optional int32 msgres = 5;</code>
			 */
			public Builder setMsgres(int value) {
				bitField0_ |= 0x00000010;
				msgres_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 msgres = 5;</code>
			 */
			public Builder clearMsgres() {
				bitField0_ = (bitField0_ & ~0x00000010);
				msgres_ = 0;
				onChanged();
				return this;
			}

			// optional string termid = 6;
			private java.lang.Object termid_ = "";

			/**
			 * <code>optional string termid = 6;</code>
			 */
			public boolean hasTermid() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			/**
			 * <code>optional string termid = 6;</code>
			 */
			public java.lang.String getTermid() {
				java.lang.Object ref = termid_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					termid_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string termid = 6;</code>
			 */
			public com.google.protobuf.ByteString getTermidBytes() {
				java.lang.Object ref = termid_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					termid_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string termid = 6;</code>
			 */
			public Builder setTermid(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000020;
				termid_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string termid = 6;</code>
			 */
			public Builder clearTermid() {
				bitField0_ = (bitField0_ & ~0x00000020);
				termid_ = getDefaultInstance().getTermid();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string termid = 6;</code>
			 */
			public Builder setTermidBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000020;
				termid_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:pbmsg.CMsgHead)
		}

		static {
			defaultInstance = new CMsgHead(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:pbmsg.CMsgHead)
	}

	public interface CMsgRegOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// optional int32 area = 1;
		/**
		 * <code>optional int32 area = 1;</code>
		 */
		boolean hasArea();

		/**
		 * <code>optional int32 area = 1;</code>
		 */
		int getArea();

		// optional int32 region = 2;
		/**
		 * <code>optional int32 region = 2;</code>
		 */
		boolean hasRegion();

		/**
		 * <code>optional int32 region = 2;</code>
		 */
		int getRegion();

		// optional int32 shop = 3;
		/**
		 * <code>optional int32 shop = 3;</code>
		 */
		boolean hasShop();

		/**
		 * <code>optional int32 shop = 3;</code>
		 */
		int getShop();

		// optional int32 ret = 4;
		/**
		 * <code>optional int32 ret = 4;</code>
		 */
		boolean hasRet();

		/**
		 * <code>optional int32 ret = 4;</code>
		 */
		int getRet();

		// optional string termid = 5;
		/**
		 * <code>optional string termid = 5;</code>
		 */
		boolean hasTermid();

		/**
		 * <code>optional string termid = 5;</code>
		 */
		java.lang.String getTermid();

		/**
		 * <code>optional string termid = 5;</code>
		 */
		com.google.protobuf.ByteString getTermidBytes();
	}

	/**
	 * Protobuf type {@code pbmsg.CMsgReg}
	 */
	public static final class CMsgReg extends
			com.google.protobuf.GeneratedMessage implements CMsgRegOrBuilder {
		// Use CMsgReg.newBuilder() to construct.
		private CMsgReg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CMsgReg(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final CMsgReg defaultInstance;

		public static CMsgReg getDefaultInstance() {
			return defaultInstance;
		}

		public CMsgReg getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CMsgReg(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						area_ = input.readInt32();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						region_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						shop_ = input.readInt32();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						ret_ = input.readInt32();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						termid_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return pbmsg.Msg.internal_static_pbmsg_CMsgReg_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return pbmsg.Msg.internal_static_pbmsg_CMsgReg_fieldAccessorTable
					.ensureFieldAccessorsInitialized(pbmsg.Msg.CMsgReg.class,
							pbmsg.Msg.CMsgReg.Builder.class);
		}

		public static com.google.protobuf.Parser<CMsgReg> PARSER = new com.google.protobuf.AbstractParser<CMsgReg>() {
			public CMsgReg parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CMsgReg(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CMsgReg> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// optional int32 area = 1;
		public static final int AREA_FIELD_NUMBER = 1;
		private int area_;

		/**
		 * <code>optional int32 area = 1;</code>
		 */
		public boolean hasArea() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>optional int32 area = 1;</code>
		 */
		public int getArea() {
			return area_;
		}

		// optional int32 region = 2;
		public static final int REGION_FIELD_NUMBER = 2;
		private int region_;

		/**
		 * <code>optional int32 region = 2;</code>
		 */
		public boolean hasRegion() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional int32 region = 2;</code>
		 */
		public int getRegion() {
			return region_;
		}

		// optional int32 shop = 3;
		public static final int SHOP_FIELD_NUMBER = 3;
		private int shop_;

		/**
		 * <code>optional int32 shop = 3;</code>
		 */
		public boolean hasShop() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional int32 shop = 3;</code>
		 */
		public int getShop() {
			return shop_;
		}

		// optional int32 ret = 4;
		public static final int RET_FIELD_NUMBER = 4;
		private int ret_;

		/**
		 * <code>optional int32 ret = 4;</code>
		 */
		public boolean hasRet() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional int32 ret = 4;</code>
		 */
		public int getRet() {
			return ret_;
		}

		// optional string termid = 5;
		public static final int TERMID_FIELD_NUMBER = 5;
		private java.lang.Object termid_;

		/**
		 * <code>optional string termid = 5;</code>
		 */
		public boolean hasTermid() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		/**
		 * <code>optional string termid = 5;</code>
		 */
		public java.lang.String getTermid() {
			java.lang.Object ref = termid_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					termid_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string termid = 5;</code>
		 */
		public com.google.protobuf.ByteString getTermidBytes() {
			java.lang.Object ref = termid_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				termid_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			area_ = 0;
			region_ = 0;
			shop_ = 0;
			ret_ = 0;
			termid_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, area_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, region_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, shop_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt32(4, ret_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getTermidBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, area_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, region_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, shop_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						4, ret_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getTermidBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static pbmsg.Msg.CMsgReg parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgReg parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static pbmsg.Msg.CMsgReg parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static pbmsg.Msg.CMsgReg parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(pbmsg.Msg.CMsgReg prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code pbmsg.CMsgReg}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				pbmsg.Msg.CMsgRegOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return pbmsg.Msg.internal_static_pbmsg_CMsgReg_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return pbmsg.Msg.internal_static_pbmsg_CMsgReg_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								pbmsg.Msg.CMsgReg.class,
								pbmsg.Msg.CMsgReg.Builder.class);
			}

			// Construct using pbmsg.Msg.CMsgReg.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				area_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				region_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				shop_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				ret_ = 0;
				bitField0_ = (bitField0_ & ~0x00000008);
				termid_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return pbmsg.Msg.internal_static_pbmsg_CMsgReg_descriptor;
			}

			public pbmsg.Msg.CMsgReg getDefaultInstanceForType() {
				return pbmsg.Msg.CMsgReg.getDefaultInstance();
			}

			public pbmsg.Msg.CMsgReg build() {
				pbmsg.Msg.CMsgReg result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public pbmsg.Msg.CMsgReg buildPartial() {
				pbmsg.Msg.CMsgReg result = new pbmsg.Msg.CMsgReg(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.area_ = area_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.region_ = region_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.shop_ = shop_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.ret_ = ret_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.termid_ = termid_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof pbmsg.Msg.CMsgReg) {
					return mergeFrom((pbmsg.Msg.CMsgReg) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(pbmsg.Msg.CMsgReg other) {
				if (other == pbmsg.Msg.CMsgReg.getDefaultInstance())
					return this;
				if (other.hasArea()) {
					setArea(other.getArea());
				}
				if (other.hasRegion()) {
					setRegion(other.getRegion());
				}
				if (other.hasShop()) {
					setShop(other.getShop());
				}
				if (other.hasRet()) {
					setRet(other.getRet());
				}
				if (other.hasTermid()) {
					bitField0_ |= 0x00000010;
					termid_ = other.termid_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				pbmsg.Msg.CMsgReg parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (pbmsg.Msg.CMsgReg) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// optional int32 area = 1;
			private int area_;

			/**
			 * <code>optional int32 area = 1;</code>
			 */
			public boolean hasArea() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>optional int32 area = 1;</code>
			 */
			public int getArea() {
				return area_;
			}

			/**
			 * <code>optional int32 area = 1;</code>
			 */
			public Builder setArea(int value) {
				bitField0_ |= 0x00000001;
				area_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 area = 1;</code>
			 */
			public Builder clearArea() {
				bitField0_ = (bitField0_ & ~0x00000001);
				area_ = 0;
				onChanged();
				return this;
			}

			// optional int32 region = 2;
			private int region_;

			/**
			 * <code>optional int32 region = 2;</code>
			 */
			public boolean hasRegion() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional int32 region = 2;</code>
			 */
			public int getRegion() {
				return region_;
			}

			/**
			 * <code>optional int32 region = 2;</code>
			 */
			public Builder setRegion(int value) {
				bitField0_ |= 0x00000002;
				region_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 region = 2;</code>
			 */
			public Builder clearRegion() {
				bitField0_ = (bitField0_ & ~0x00000002);
				region_ = 0;
				onChanged();
				return this;
			}

			// optional int32 shop = 3;
			private int shop_;

			/**
			 * <code>optional int32 shop = 3;</code>
			 */
			public boolean hasShop() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional int32 shop = 3;</code>
			 */
			public int getShop() {
				return shop_;
			}

			/**
			 * <code>optional int32 shop = 3;</code>
			 */
			public Builder setShop(int value) {
				bitField0_ |= 0x00000004;
				shop_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 shop = 3;</code>
			 */
			public Builder clearShop() {
				bitField0_ = (bitField0_ & ~0x00000004);
				shop_ = 0;
				onChanged();
				return this;
			}

			// optional int32 ret = 4;
			private int ret_;

			/**
			 * <code>optional int32 ret = 4;</code>
			 */
			public boolean hasRet() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional int32 ret = 4;</code>
			 */
			public int getRet() {
				return ret_;
			}

			/**
			 * <code>optional int32 ret = 4;</code>
			 */
			public Builder setRet(int value) {
				bitField0_ |= 0x00000008;
				ret_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int32 ret = 4;</code>
			 */
			public Builder clearRet() {
				bitField0_ = (bitField0_ & ~0x00000008);
				ret_ = 0;
				onChanged();
				return this;
			}

			// optional string termid = 5;
			private java.lang.Object termid_ = "";

			/**
			 * <code>optional string termid = 5;</code>
			 */
			public boolean hasTermid() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			/**
			 * <code>optional string termid = 5;</code>
			 */
			public java.lang.String getTermid() {
				java.lang.Object ref = termid_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					termid_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string termid = 5;</code>
			 */
			public com.google.protobuf.ByteString getTermidBytes() {
				java.lang.Object ref = termid_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					termid_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string termid = 5;</code>
			 */
			public Builder setTermid(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				termid_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string termid = 5;</code>
			 */
			public Builder clearTermid() {
				bitField0_ = (bitField0_ & ~0x00000010);
				termid_ = getDefaultInstance().getTermid();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string termid = 5;</code>
			 */
			public Builder setTermidBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				termid_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:pbmsg.CMsgReg)
		}

		static {
			defaultInstance = new CMsgReg(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:pbmsg.CMsgReg)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_pbmsg_CMsg_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_pbmsg_CMsg_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_pbmsg_CMsgHead_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_pbmsg_CMsgHead_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_pbmsg_CMsgReg_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_pbmsg_CMsgReg_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\tmsg.proto\022\005pbmsg\"(\n\004CMsg\022\017\n\007msghead\030\001 "
				+ "\002(\t\022\017\n\007msgbody\030\002 \002(\t\"p\n\010CMsgHead\022\016\n\006msgl"
				+ "en\030\001 \001(\005\022\017\n\007msgtype\030\002 \001(\005\022\016\n\006msgseq\030\003 \001("
				+ "\005\022\023\n\013termversion\030\004 \001(\005\022\016\n\006msgres\030\005 \001(\005\022\016"
				+ "\n\006termid\030\006 \001(\t\"R\n\007CMsgReg\022\014\n\004area\030\001 \001(\005\022"
				+ "\016\n\006region\030\002 \001(\005\022\014\n\004shop\030\003 \001(\005\022\013\n\003ret\030\004 \001"
				+ "(\005\022\016\n\006termid\030\005 \001(\t" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_pbmsg_CMsg_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_pbmsg_CMsg_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_pbmsg_CMsg_descriptor,
						new java.lang.String[] { "Msghead", "Msgbody", });
				internal_static_pbmsg_CMsgHead_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_pbmsg_CMsgHead_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_pbmsg_CMsgHead_descriptor,
						new java.lang.String[] { "Msglen", "Msgtype", "Msgseq",
								"Termversion", "Msgres", "Termid", });
				internal_static_pbmsg_CMsgReg_descriptor = getDescriptor()
						.getMessageTypes().get(2);
				internal_static_pbmsg_CMsgReg_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_pbmsg_CMsgReg_descriptor,
						new java.lang.String[] { "Area", "Region", "Shop",
								"Ret", "Termid", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
